Repository woowacourse-teams/2022-nae-pyeon, pull requests merged in 2022-07, with the labels that each got.

#9 refactor: 레포지토리 계층 추상화 및 이름 변경
  backend/README.md
  backend/src/main/java/com/woowacourse/naepyeon/DummyConfig.java
  backend/src/main/java/com/woowacourse/naepyeon/TestDataInit.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaMemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaMessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaRollingpaperRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamMemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/MemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/MessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/RollingpaperRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamMemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/MemberJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/MessageJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/RollingpaperJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamMemberJpaDao.java
Labels: 백엔드, 리팩토링

#15 chore: 프론트엔드 환경설정
  .gitignore
  frontend/.eslintrc.json
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/babel.config.js
  frontend/package.json
  frontend/public/index.html
  frontend/public/mockServiceWorker.js
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/mocks/browser.js
  frontend/src/mocks/handlers.js
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 프론트엔드, 설정

#23 feat: 롤링페이퍼 생성 페이지 UI 구현
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Button.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/IconButton.tsx
  frontend/src/components/LabeledInput.tsx
  frontend/src/components/PageTitle.tsx
  frontend/src/components/SearchInput.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/stories/Button.stories.jsx
  frontend/src/stories/Header.stories.jsx
  frontend/src/stories/IconButton.stories.jsx
  frontend/src/stories/LabeledInput.stories.jsx
  frontend/src/stories/PageTitle.stories.jsx
  frontend/src/stories/SearchInput.stories.jsx
  frontend/src/styles/reset.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 프론트엔드, UI

#25 feat: 롤링페이퍼 페이지 UI 구현
  frontend/src/App.tsx
  frontend/src/components/IconButton.tsx
  frontend/src/components/LetterPaper.tsx
  frontend/src/components/RollingpaperMessage.tsx
  frontend/src/pages/RollingpaperPage.tsx
  frontend/src/stories/LetterPaper.stories.jsx
  frontend/src/stories/RollingpaperMessage.stories.jsx
Labels: 프론트엔드, UI

#20 feat: 모임 CRUD 기능을 구현
  backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/TeamRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Team.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MemberService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/TeamResponse.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/JpaTeamRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 기능

#33 docs: feature 이슈 템플릿 작성
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 문서

#39 chore: cors 문제 처리하는 로직 작성
  backend/src/main/java/com/woowacourse/naepyeon/config/WebConfig.java
Labels: 백엔드, 설정

#43 feat: 롤링페이퍼 관련 API 요청 및 응답 처리 로직을 구현
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Button.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/IconButton.tsx
  frontend/src/components/LabeledInput.tsx
  frontend/src/components/LetterPaper.tsx
  frontend/src/components/PageTitle.tsx
  frontend/src/components/RollingpaperMessage.tsx
  frontend/src/components/SearchInput.tsx
  frontend/src/components/TextArea.tsx
  frontend/src/index.tsx
  frontend/src/mocks/dummy/rollingpapers.json
  frontend/src/mocks/handlers.js
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/RollingpaperPage.tsx
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 프론트엔드, 기능

#42 feat: 컨트롤러에 더미데이터로 응답값을 전달하도록 변경한다.
  backend/src/main/java/com/woowacourse/naepyeon/TestDataInit.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/MessageController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/RollingpaperController.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
Labels: 백엔드, 기능

#37 feat: 회원을 모임에 가입시키는 기능 구현
  backend/src/main/java/com/woowacourse/naepyeon/domain/TeamMember.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamMemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamMemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamMemberJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MemberService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamMemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 기능

#51 fix: @GeneratedValue를 IDENTITY로 수정했을 때 테스트 격리를 시킨다.
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceTest.java
Labels: 백엔드, 버그, 테스트

#55 fix: 메시지 삭제 시, 롤링페이퍼와 연관해서 삭제 관련된 버그 수정
  backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/TeamMember.java
Labels: 백엔드, 버그

#57 feat: osiv 옵션을 해제한다.
  backend/src/main/resources/application.yml
Labels: 백엔드, 설정

#58 fix: 롤링페이퍼 메시지 상세보기에서 줄바꿈이 적용 안 되는 문제 해결
  frontend/src/components/RollingpaperMessage.tsx
  frontend/src/components/RollingpaperMessageDetail.tsx
  frontend/src/mocks/dummy/rollingpapers.json
  frontend/src/mocks/handlers.js
Labels: 프론트엔드, UI

#59 feat: 컬러 Theme와 Font를 적용
  frontend/.eslintrc.json
  frontend/src/App.tsx
  frontend/src/assets/fonts/SeoulNamsanM.ttf
  frontend/src/components/LabeledInput.tsx
  frontend/src/components/LetterPaper.tsx
  frontend/src/components/RollingpaperMessage.tsx
  frontend/src/components/RollingpaperMessageDetail.tsx
  frontend/src/components/SearchInput.tsx
  frontend/src/components/TextArea.tsx
  frontend/src/styles/font.ts
  frontend/src/styles/reset.ts
  frontend/src/styles/theme.ts
  frontend/src/types/emotion.d.ts
  frontend/src/types/font.d.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: 프론트엔드, UI

#68 feat: SearchInput 컴포넌트를 보완
  frontend/src/components/RollingpaperMessageDetail.tsx
  frontend/src/components/SearchInput.tsx
  frontend/src/pages/MessageDetailPage.tsx
  frontend/src/pages/MessageEditPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/styles/reset.ts
Labels: 프론트엔드, 리팩토링, UI

#71 feat: react query 적용
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Button.tsx
  frontend/src/mocks/handlers.js
  frontend/src/pages/MessageDetailPage.tsx
  frontend/src/pages/MessageEditPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/RollingpaperPage.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 기능

#72 feat: 도메인에 대한 검증과 도메인 테스트를 추가한다.
  backend/src/main/java/com/woowacourse/naepyeon/TestDataInit.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Rollingpaper.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Team.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/DuplicateMemberEmailException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMemberPasswordLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMemberUsernameLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMessageContentLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedRollingpaperNameLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedTeamNameLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberEmailException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberPasswordException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberUsernameException.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/MemberTest.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/MessageTest.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/RollingpaperTest.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/TeamTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamMemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 기능, 문서, 테스트

#75 feat: button 디자인
  frontend/.storybook/preview.js
  frontend/src/components/Button.tsx
  frontend/src/components/LineButton.tsx
  frontend/src/components/TextArea.tsx
  frontend/src/pages/MessageEditPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/stories/Button.stories.jsx
  frontend/src/stories/LetterPaper.stories.jsx
  frontend/src/stories/LineButton.stories.jsx
Labels: 프론트엔드, 기능, UI

#77 refactor: 더미데이터를 삭제하고 정규표현식 코드를 개선하여 성능을 향상한다.
  backend/src/main/java/com/woowacourse/naepyeon/DummyConfig.java
  backend/src/main/java/com/woowacourse/naepyeon/TestDataInit.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/MessageController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/RollingpaperController.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
Labels: 백엔드, 리팩토링

#78 feat: 모임 생성 페이지 UI
  frontend/src/components/LabeledInput.tsx
  frontend/src/components/LabeledRadio.tsx
  frontend/src/components/LabeledTextArea.tsx
  frontend/src/pages/TeamCreationPage.tsx
  frontend/src/stories/LabeledRadio.stories.jsx
  frontend/src/stories/LabeledTextArea.stories.jsx
Labels: 프론트엔드, UI

#87 feat: 이미 존재하는 이메일로 회원가입을 시도할 경우 예외가 발생한다.
  backend/src/main/java/com/woowacourse/naepyeon/controller/ControllerAdvice.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/MemberController.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/DuplicateMemberEmailException.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaMemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/MemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/MemberJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MemberService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/MemberResponseDto.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamMemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 기능

#91 feat: 모임 생성 mocking 및 API 연결
  frontend/src/components/LabeledRadio.tsx
  frontend/src/mocks/handlers.js
  frontend/src/pages/TeamCreationPage.tsx
  frontend/src/stories/LabeledRadio.stories.jsx
Labels: 프론트엔드, 기능, UI

#90 feat: 예외 응답 폼 변경
  backend/src/main/java/com/woowacourse/naepyeon/controller/ControllerAdvice.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/ErrorResponse.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MemberRegisterRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MemberUpdateRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MessageRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MessageUpdateContentRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/RollingpaperCreateRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/RollingpaperUpdateRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/TeamRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/DuplicateMemberEmailException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMemberPasswordLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMemberUsernameLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMessageContentLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedRollingpaperNameLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedTeamNameLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberEmailException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberPasswordException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberUsernameException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/NaePyeonException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundMemberException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundMessageException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundRollingpaperException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundTeamException.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamMemberRepositoryTest.java
Labels: 백엔드

#96 feat: 공통된 페이지 레이아웃 추가
  frontend/src/App.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/PageContainer.tsx
  frontend/src/components/PageTitle.tsx
  frontend/src/pages/MessageDetailPage.tsx
  frontend/src/pages/MessageEditPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/RollingpaperPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/src/pages/TeamCreationPage.tsx
Labels: 프론트엔드, UI

#97 refactor: axios instance 적용
  frontend/src/api/index.ts
  frontend/src/components/LabeledRadio.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/MessageDetailPage.tsx
  frontend/src/pages/MessageEditPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/RollingpaperPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/src/pages/TeamCreationPage.tsx
Labels: 프론트엔드, 리팩토링

#99 feat: Input, Button 컴포넌트 보완
  frontend/src/components/Button.tsx
  frontend/src/components/LabeledInput.tsx
  frontend/src/components/LabeledRadio.tsx
  frontend/src/components/LineButton.tsx
  frontend/src/components/RollingpaperMessage.tsx
  frontend/src/components/SearchInput.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/src/styles/theme.ts
Labels: 프론트엔드, UI

#98 feat: 로그인 기능 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/woowacourse/naepyeon/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/MemberController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/auth/AuthController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/auth/AuthenticationPrincipal.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/auth/AuthenticationPrincipalArgumentResolver.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/auth/LoginInterceptor.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/LoginMemberRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/TokenRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidLoginException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/TokenInvalidExpiredException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/TokenInvalidFormException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/TokenInvalidSecretKeyException.java
  backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/TokenRequestDto.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/TokenResponseDto.java
  backend/src/main/java/com/woowacourse/naepyeon/support/AuthorizationExtractor.java
  backend/src/main/java/com/woowacourse/naepyeon/support/JwtTokenProvider.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/LoginAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/support/JwtTokenProviderTest.java
Labels: 백엔드, 기능

#109 feat: main page UI 구현
  frontend/src/App.tsx
  frontend/src/components/MainCard.tsx
  frontend/src/components/PlusButton.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/stories/MainCard.stories.jsx
  frontend/src/stories/PlusButton.stories.jsx
Labels: 프론트엔드, UI

#111 feat: 전체 모임 목록 페이지 UI
  frontend/src/App.tsx
  frontend/src/assets/images/kakao.png
  frontend/src/assets/images/logo.png
  frontend/src/components/PasswordInput.tsx
  frontend/src/components/Search.tsx
  frontend/src/components/SocialLoginButton.tsx
  frontend/src/components/TeamCard.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/TeamSearchPage.tsx
  frontend/src/stories/PasswordInput.stories.jsx
  frontend/src/stories/Search.stories.jsx
  frontend/src/stories/SocialLoginButton.stories.jsx
  frontend/src/stories/TeamCard.stories.jsx
  frontend/src/types/image.d.ts
  frontend/webpack.config.js
Labels: 프론트엔드, UI

#110 feat: 로그인 페이지 UI 구현
  frontend/src/components/AutoCompleteInput.tsx
  frontend/src/components/Logo.tsx
  frontend/src/components/PasswordInput.tsx
  frontend/src/components/Search.tsx
  frontend/src/components/SearchInput.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/TeamSearchPage.tsx
  frontend/src/stories/AutoCompleteInput.jsx
  frontend/src/stories/Search.stories.jsx
  frontend/src/stories/SearchInput.stories.jsx
Labels: 프론트엔드, UI

#113 feat: 모임 상세보기 페이지 UI 구현
  frontend/src/App.tsx
  frontend/src/components/Modal.tsx
  frontend/src/components/RollingpaperList.tsx
  frontend/src/components/RollingpaperListItem.tsx
  frontend/src/components/TeamJoinModalForm.tsx
  frontend/src/components/TeamJoinSection.tsx
  frontend/src/components/UnderlineInput.tsx
  frontend/src/pages/TeamDetailPage.tsx
  frontend/src/stories/Modal.stories.jsx
  frontend/src/stories/RollingpaperList.stories.jsx
  frontend/src/stories/RollingpaperListItem.stories.jsx
  frontend/src/stories/TeamJoinModalForm.stories.jsx
  frontend/src/stories/TeamJoinSection.stories.jsx
  frontend/src/stories/UnderlineInput.stories.jsx
Labels: 프론트엔드, UI

#115 feat: header 보완
  frontend/src/App.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/PageTitle.tsx
  frontend/src/components/PageTitleWithBackButton.tsx
  frontend/src/components/SearchInput.tsx
  frontend/src/pages/HeaderLayoutPage.tsx
  frontend/src/pages/MessageDetailPage.tsx
  frontend/src/pages/MessageEditPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/RollingpaperPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/src/pages/TeamCreationPage.tsx
  frontend/src/stories/AutoCompleteInput.stories.jsx
  frontend/src/stories/Header.stories.jsx
  frontend/src/stories/PageTitleWithBackButton.stories.jsx
  frontend/src/types/image.d.ts
Labels: 프론트엔드, 리팩토링, UI

#122 feat: 모임 상세보기 페이지 API 요청 및 응답 처리 로직 구현
  frontend/src/components/TeamJoinModalForm.tsx
  frontend/src/components/TeamJoinSection.tsx
  frontend/src/mocks/handlers.js
  frontend/src/pages/TeamDetailPage.tsx
Labels: 프론트엔드, 기능

#123 feat: 회원가입 페이지의 회원가입 요청 핸들러 로직 수정
  frontend/src/pages/SignUpPage.tsx
Labels: 프론트엔드, 기능

#120 feat: 로그인, 메인, 전체 모임 보기 api logic 추가
  frontend/src/components/PasswordInput.tsx
  frontend/src/components/SearchInput.tsx
  frontend/src/mocks/dummy/myTeams.json
  frontend/src/mocks/dummy/totalTeams.json
  frontend/src/mocks/handlers.js
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/TeamCreationPage.tsx
  frontend/src/pages/TeamSearchPage.tsx
Labels: 프론트엔드, 기능, 리팩토링

#116 test: 회원 관련 인수 테스트를 작성한다.
  backend/src/main/java/com/woowacourse/naepyeon/controller/MemberController.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MemberService.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
Labels: 백엔드, 리팩토링, 테스트

#121 feat: 모임관련 기능 추가 및 인수테스트 보강
  backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/DuplicateTeamNameException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/DuplicateTeamPaticipateException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedNicknameLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamMemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamMemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamMemberJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/TeamResponseDto.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/TeamsResponseDto.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 기능, 리팩토링, 테스트

#127 feat: 로그인 유저 정보 관련 로직 구현
  frontend/src/App.tsx
  frontend/src/api/index.ts
  frontend/src/components/Header.tsx
  frontend/src/components/RequireLogin.tsx
  frontend/src/components/RequireLogout.tsx
  frontend/src/context/UserContext.tsx
  frontend/src/mocks/handlers.js
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MessageDetailPage.tsx
  frontend/src/pages/MessageEditPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/RollingpaperPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/src/pages/TeamCreationPage.tsx
  frontend/src/pages/TeamDetailPage.tsx
  frontend/src/pages/TeamSearchPage.tsx
  frontend/src/util/cookie.ts
Labels: 프론트엔드, 기능

#129 feat: 라우팅 수정
  frontend/src/App.tsx
  frontend/src/components/MyTeamCard.tsx
  frontend/src/components/TeamCreateButton.tsx
  frontend/src/components/TeamRollingpaperList.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/TeamDetailPage.tsx
  frontend/src/stories/MyTeamCard.stories.jsx
  frontend/src/stories/PlusButton.stories.jsx
  frontend/src/stories/TeamCreateButton.stories.jsx
  frontend/src/stories/TeamRollingpaperList.stories.jsx
Labels: 프론트엔드, 기능, 리팩토링

#126 feat: 롤링페이퍼 인수 테스트 작성
  backend/src/main/java/com/woowacourse/naepyeon/controller/MemberController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/RollingpaperController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/RollingpaperCreateRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundMemberException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundTeamMemberException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/UncertificationTeamMemberException.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaRollingpaperRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/RollingpaperRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/RollingpaperJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/RollingpaperAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
Labels: 백엔드, 기능, 리팩토링, 테스트

#133 refactor: 롤링페이퍼 컨트롤러 메서드명 및 파라미터명 변경
  backend/src/main/java/com/woowacourse/naepyeon/controller/RollingpaperController.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
Labels: 백엔드, 리팩토링

#136 feat: 모임관련 인가로직, 모임에 가입한 회원 목록 조회 기능 구현
  backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/UncertificationTeamMemberException.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamMemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamMemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamMemberJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/JoinedMemberResponseDto.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/JoinedMembersResponseDto.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/TeamResponseDto.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 기능

#141 feat: API 응답 처리 로직을 수정
  frontend/src/App.tsx
  frontend/src/components/TeamJoinModalForm.tsx
  frontend/src/components/TeamRollingpaperList.tsx
  frontend/src/mocks/browser.js
  frontend/src/mocks/dummy/myTeams.json
  frontend/src/mocks/handlers.js
  frontend/src/mocks/handlers/index.js
  frontend/src/mocks/handlers/memberHandlers.js
  frontend/src/mocks/handlers/messageHandlers.js
  frontend/src/mocks/handlers/rollingpaperHandlers.js
  frontend/src/mocks/handlers/teamHandlers.js
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MessageDetailPage.tsx
  frontend/src/pages/MessageEditPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/RollingpaperPage.tsx
  frontend/src/pages/TeamCreationPage.tsx
  frontend/src/pages/TeamDetailPage.tsx
  frontend/src/pages/TeamSearchPage.tsx
Labels: 프론트엔드, 기능, 리팩토링

#143 feat: API 에러 응답 처리 및 form 입력 유효성 검사를 추가한다
  frontend/src/components/LabeledTextArea.tsx
  frontend/src/components/TeamRollingpaperList.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MessageDetailPage.tsx
  frontend/src/pages/MessageEditPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/RollingpaperPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/src/pages/TeamCreationPage.tsx
  frontend/src/pages/TeamDetailPage.tsx
  frontend/src/pages/TeamSearchPage.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 기능

#142 feat: Feature/137 paper adressee nickname
  backend/src/main/java/com/woowacourse/naepyeon/domain/Rollingpaper.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamParticipationRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamParticipationRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamParticipationJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/RollingpaperPreviewResponseDto.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/RollingpaperTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 버그, 기능

#145 feat: 모임 생성시 닉네임을 받도록 수정
  frontend/src/components/LabeledTextArea.tsx
  frontend/src/pages/TeamCreationPage.tsx
Labels: 프론트엔드, 기능, UI

#146 test: 모임 관련 서비스, 레포지토리 테스트 보충
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamParticipationRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamParticipationRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamParticipationJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 리팩토링, 테스트

#147 feat: 팀 생성시 팀 생성한 사람의 팀 닉네임 받도록 변경
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/TeamRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/RollingpaperPreviewResponseDto.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/RollingpaperAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 기능

#149 refactor: 디미터 법칙 준수^^
  backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/RollingpaperTest.java
Labels: 백엔드, 리팩토링

#153 fix: message 삭제 시 작성된 롤링페이퍼로 이동
  frontend/src/pages/MessageDetailPage.tsx
Labels: 프론트엔드, 버그

#154 fix: RequireLogin, RequireLogout 컴포넌트 사용 위치 변경
  frontend/src/App.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MessageDetailPage.tsx
  frontend/src/pages/MessageEditPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/RollingpaperPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/src/pages/TeamCreationPage.tsx
  frontend/src/pages/TeamDetailPage.tsx
  frontend/src/pages/TeamSearchPage.tsx
Labels: 프론트엔드, 버그

#156 feat: 스타일링 수정
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/assets/images/logo.png
  frontend/src/components/Header.tsx
  frontend/src/components/IconButton.tsx
  frontend/src/components/Logo.tsx
  frontend/src/components/Modal.tsx
  frontend/src/components/MyTeamCard.tsx
  frontend/src/components/TeamCreateButton.tsx
  frontend/src/mocks/dummy/myTeams.json
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/TeamSearchPage.tsx
Labels: 프론트엔드, 리팩토링, UI

#159 chore: package.json script 변경
  frontend/package.json
Labels: 프론트엔드, 설정

#163 chore: deploy 설정파일 추가
  backend/src/main/resources/application-deploy.yml
Labels: 백엔드, 설정, 중요

#164 feat: production 모드 설정
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/assets/images/logo_background.png
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 프론트엔드, 설정

#161 feat: 메시지 인수 테스트 추가 및 메시지 닉네임 보이게 수정
  backend/src/main/java/com/woowacourse/naepyeon/controller/MessageController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MessageRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/NotAuthorException.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MessageAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
Labels: 백엔드, 기능, 테스트

#168 fix: webpack과 style을 수정한다
  frontend/package.json
  frontend/public/logo.png
  frontend/src/assets/fonts/SeoulNamsanM.ttf
  frontend/src/components/RollingpaperMessageDetail.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/styles/font.ts
  frontend/src/types/font.d.ts
  frontend/webpack.common.js
Labels: 프론트엔드, 버그, 리팩토링

#177 feat: svg 사용 설정 및 react-icons 제거
  frontend/.storybook/main.js
  frontend/package.json
  frontend/src/assets/icons/bx-chevron-left.svg
  frontend/src/assets/icons/bx-hide.svg
  frontend/src/assets/icons/bx-pencil.svg
  frontend/src/assets/icons/bx-plus.svg
  frontend/src/assets/icons/bx-search.svg
  frontend/src/assets/icons/bx-show.svg
  frontend/src/assets/icons/bx-trash.svg
  frontend/src/assets/icons/bx-user.svg
  frontend/src/assets/icons/bx-x.svg
  frontend/src/assets/icons/bxs-error.svg
  frontend/src/components/AutoCompleteInput.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/LabeledInput.tsx
  frontend/src/components/LetterPaper.tsx
  frontend/src/components/Modal.tsx
  frontend/src/components/PageTitleWithBackButton.tsx
  frontend/src/components/PasswordInput.tsx
  frontend/src/components/RollingpaperMessageDetail.tsx
  frontend/src/components/SearchInput.tsx
  frontend/src/components/TeamCreateButton.tsx
  frontend/src/components/TeamJoinSection.tsx
  frontend/src/components/TeamRollingpaperList.tsx
  frontend/src/components/UnderlineInput.tsx
  frontend/src/stories/IconButton.stories.jsx
  frontend/webpack.common.js
Labels: 프론트엔드, UI

#175 feat: 생성일자, 수정일자 필드 추가
  backend/src/main/java/com/woowacourse/naepyeon/config/JpaAuditingConfig.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/BaseEntity.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Rollingpaper.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Team.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamRepositoryTest.java
Labels: 백엔드, 기능

#189 feat: webpack과 dotenv 설정
  .gitignore
  frontend/package.json
  frontend/src/api/index.ts
  frontend/src/constants/index.ts
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 프론트엔드, 설정

#184 feat: 모임 마이페이지 기능 구현
  backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/UpdateTeamParticipantRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/DuplicateNicknameException.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamParticipationRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamParticipationRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamParticipationJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/TeamMemberResponseDto.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 기능

#197 chore: flyway 적용 및 개발환경 DB를 H2에서 MYSQL로 마이그레이션
  backend/build.gradle
  backend/src/main/java/com/woowacourse/naepyeon/domain/BaseEntity.java
  backend/src/main/resources/application-deploy.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/V1__init.sql
Labels: 백엔드, 인프라, 설정

#186 feat: mypage UI를 구현한다
  frontend/src/App.tsx
  frontend/src/assets/icons/bx-chevron-right.svg
  frontend/src/components/MyPageRollingpaperListPaging.tsx
  frontend/src/components/MyPageTab.tsx
  frontend/src/components/MyPageWrittenMessageListPaging.tsx
  frontend/src/components/Paging.tsx
  frontend/src/components/ReceivedRollingpaperCard.tsx
  frontend/src/components/UserProfile.tsx
  frontend/src/components/WrittenMessageCard.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/stories/IconButton.stories.jsx
  frontend/src/stories/MyPageTab.jsx
  frontend/src/stories/Paging.stories.jsx
  frontend/src/stories/ReceivedRollingpaperCard.stories.jsx
  frontend/src/stories/UserProfile.stories.jsx
  frontend/src/stories/WrittenMessageCard.stories.jsx
  frontend/src/types/index.ts
Labels: 프론트엔드, UI

#194 feat: 롤링페이퍼 페이지 UI 수정 및 새 메시지 작성 컴포넌트 UI 구현
  frontend/src/assets/icons/bx-check.svg
  frontend/src/components/LetterPaper.tsx
  frontend/src/components/MessageColorPicker.tsx
  frontend/src/components/MessageForm.tsx
  frontend/src/components/MessageTextArea.tsx
  frontend/src/components/RollingpaperMessage.tsx
  frontend/src/mocks/dummy/rollingpapers.json
  frontend/src/stories/MessageColorPicker.stories.jsx
  frontend/src/stories/MessageForm.stories.jsx
  frontend/src/stories/MessageTextArea.stories.jsx
  frontend/src/util/index.ts
Labels: 프론트엔드, UI

#209 fix: V2 네이밍 버그를 수정한다.
  backend/src/main/resources/db/migration/V2__add_baseEntity.sql
Labels: 백엔드, 버그, 인프라

#212 feat: 로그인 로직 수정
  frontend/src/api/index.ts
  frontend/src/components/Header.tsx
  frontend/src/components/UserProfile.tsx
  frontend/src/context/UserContext.tsx
  frontend/src/mocks/handlers/memberHandlers.js
  frontend/src/pages/LoginPage.tsx
  frontend/src/util/cookie.ts
Labels: 프론트엔드, 기능, 리팩토링

#214 fix: 자동 로그인 에러 수정
  frontend/src/context/UserContext.tsx
Labels: 프론트엔드, 버그

#218 feat: 전체 팀 검색 기능 구현
  frontend/src/constants/index.ts
  frontend/src/hooks/useIntersect.tsx
  frontend/src/mocks/dummy/totalTeams.json
  frontend/src/mocks/handlers/teamHandlers.js
  frontend/src/pages/TeamSearchPage.tsx
Labels: 프론트엔드, 기능, UI

#215 feat: 메시지 관련 로직 작성
  frontend/src/components/LetterPaper.tsx
  frontend/src/components/MessageColorPicker.tsx
  frontend/src/components/MessageForm.tsx
  frontend/src/components/MessageTextArea.tsx
  frontend/src/components/RollingpaperMessage.tsx
  frontend/src/constants/index.ts
  frontend/src/mocks/dummy/rollingpapers.json
  frontend/src/pages/TeamCreationPage.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 기능

#219 feat: 마이페이지 API 요청 및 응답 로직 구현
  frontend/src/components/MyPagePaginatedMessageList.tsx
  frontend/src/components/MyPagePaginatedRollingpaperList.tsx
  frontend/src/components/UserProfile.tsx
  frontend/src/mocks/dummy/receivedRollingpapers.json
  frontend/src/mocks/dummy/sentMessages.json
  frontend/src/mocks/handlers/memberHandlers.js
  frontend/src/pages/MyPage.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 기능

#221 chore: react query version 업그레이드
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/LetterPaper.tsx
  frontend/src/components/RollingpaperMessage.tsx
  frontend/src/components/TeamJoinModalForm.tsx
  frontend/src/components/TeamRollingpaperList.tsx
  frontend/src/components/UserProfile.tsx
  frontend/src/context/UserContext.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/MessageDetailPage.tsx
  frontend/src/pages/MessageEditPage.tsx
  frontend/src/pages/MessageWritePage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/RollingpaperCreationPage.tsx
  frontend/src/pages/RollingpaperPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/src/pages/TeamCreationPage.tsx
  frontend/src/pages/TeamDetailPage.tsx
  frontend/src/pages/TeamSearchPage.tsx
  frontend/yarn.lock
Labels: 프론트엔드, 설정

#230 feat: 모임 색상 선택 변경
  frontend/src/pages/TeamCreationPage/index.tsx
Labels: 프론트엔드, 버그

#231 feat: 마이페이지 버튼 클릭 시 mypage로 라우팅 추가
  frontend/src/components/Header.tsx
Labels: 프론트엔드, 기능
