Repository woowacourse-teams/2022-nae-pyeon, pull requests merged in 2022-10, with the labels that each got.

#504 fix: LabeledSwitch에서 발생하는 경고를 해결
  frontend/src/components/LabeledSwitch.tsx
Labels: 프론트엔드, 버그

#507 feat: google oauth를 연결한다
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/PolicyPage/index.tsx
Labels: 프론트엔드, 기능

#500 feat: 엔티티 연관관계를 개선하고 복잡한 쿼리를 리팩터링한다.
  backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Rollingpaper.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryImpl.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/teamparticipation/TeamParticipationRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/teamparticipation/TeamParticipationRepositoryImpl.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/RollingpaperPreviewResponseDto.java
  backend/src/main/resources/db/migration/V0.4.4__entity_rollingpaper_add_team_participation.sql
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/config/DatabaseCleaner.java
  backend/src/test/java/com/woowacourse/naepyeon/document/MemberControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 버그, 리팩토링, 중요

#501 feat: 메인페이지 UI를 개선
  frontend/__tests__/MainPage.test.tsx
  frontend/src/components/EmptyRollingpaperList.tsx
  frontend/src/components/LineButton.tsx
  frontend/src/components/RollinpaperListItem.tsx
  frontend/src/components/RoundButtonWithDescription.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/MainPage/components/EmptyMyTeamList.tsx
  frontend/src/pages/MainPage/components/MyTeamCard.tsx
  frontend/src/pages/MainPage/components/MyTeamsSection.tsx
  frontend/src/pages/MainPage/components/ReceivedRollingpapersSection.tsx
  frontend/src/pages/MainPage/components/SectionHeader.tsx
  frontend/src/pages/MainPage/components/TeamCreateButton.stories.jsx
  frontend/src/pages/MainPage/components/TeamCreateButton.tsx
  frontend/src/pages/MainPage/hooks/useReadMyRollingpapers.tsx
  frontend/src/pages/MainPage/hooks/useReadMyTeams.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/MyPage/components/RollingpaperList.tsx
  frontend/src/pages/MyPage/components/RollingpaperListItem.stories.jsx
Labels: 프론트엔드, UI

#519 refactor: 초대코드 변수명을 변경한다.
  frontend/src/App.tsx
  frontend/src/api/team.ts
  frontend/src/constants/index.ts
  frontend/src/mocks/handlers/teamHandlers.js
  frontend/src/pages/GoogleRedirectPage/index.tsx
  frontend/src/pages/InvitePage/hooks/useCheckLogin.tsx
  frontend/src/pages/InvitePage/hooks/useCreateTeamWithInviteCode.tsx
  frontend/src/pages/InvitePage/hooks/useReadTeamDetailWithInviteCode.tsx
  frontend/src/pages/InvitePage/hooks/useReadTeamDetailWithInviteToken.tsx
  frontend/src/pages/InvitePage/index.tsx
  frontend/src/pages/KakaoRedirectPage/hooks/useCreateKakaoOauthLogin.tsx
  frontend/src/pages/KakaoRedirectPage/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/InviteModal.tsx
  frontend/src/pages/TeamDetailPage/hooks/useCreateInviteLink.tsx
  frontend/src/types/apiRequest.ts
  frontend/src/types/apiResponse.ts
Labels: 프론트엔드, 리팩토링

#527 feat: 메세지 좋아요 기능을 구현
  backend/src/docs/asciidoc/errorCodes.adoc
  backend/src/docs/asciidoc/messages.adoc
  backend/src/main/java/com/woowacourse/naepyeon/controller/MessageController.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/message/Message.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/message/MessageLike.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/ExceedMessageContentLengthException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidCancelLikeMessageException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidLikeMessageException.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/messagelike/MessageLikeRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/messagelike/MessageLikeRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/messagelike/MessageLikeRepositoryImpl.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/MessageLikeResponseDto.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/MessageResponseDto.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/WrittenMessageResponseDto.java
  backend/src/main/resources/db/migration/V0.4.5__message_like.sql
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MessageAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/MessageControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/MessageTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
Labels: 백엔드, 기능

#524 feat: 롤링페이퍼 정렬 api 구현
  backend/src/docs/asciidoc/rollingpapers.adoc
  backend/src/main/java/com/woowacourse/naepyeon/controller/RollingpaperController.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Recipient.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Rollingpaper.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryImpl.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/test/java/com/woowacourse/naepyeon/document/RollingpaperControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
Labels: 백엔드, 기능

#514 feat: 롤링페이퍼 생성 플로우 UI 구현
  frontend/src/App.tsx
  frontend/src/assets/icons/bx-chevron-left-circle.svg
  frontend/src/assets/icons/bx-chevron-right-circle.svg
  frontend/src/components/ControlDots.tsx
  frontend/src/components/IconButton.tsx
  frontend/src/components/LabeledInput.tsx
  frontend/src/components/MyTeamCard.tsx
  frontend/src/components/PageTitleWithBackButton.tsx
  frontend/src/components/stories/MyTeamCard.stories.jsx
  frontend/src/constants/index.ts
  frontend/src/pages/MainPage/components/MyTeamsSection.tsx
  frontend/src/pages/MainPage/hooks/useReadMyTeams.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/PolicyPage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperCreationPage/components/RecipientBox.tsx
  frontend/src/pages/RollingpaperCreationPage/components/Step1.tsx
  frontend/src/pages/RollingpaperCreationPage/components/Step2.tsx
  frontend/src/pages/RollingpaperCreationPage/components/Step3.tsx
  frontend/src/pages/RollingpaperCreationPage/components/StepTitleWithLayout.tsx
  frontend/src/pages/RollingpaperCreationPage/components/TeamRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useCreateMemberRolliingpaper.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useCreateTeamRollingpaper.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useReadMyTeam.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useReadTeamMembers.tsx
  frontend/src/pages/RollingpaperCreationPage/index.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
  frontend/src/pages/TeamCreationPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
  frontend/src/pages/TeamDetailPage/hooks/useCreateInviteLink.tsx
Labels: 프론트엔드, 기능, UI

#523 feat: 좋아요 UI 및 기능 추가
  frontend/src/api/message.ts
  frontend/src/assets/icons/bx-heart-empty.svg
  frontend/src/assets/icons/bx-heart-fill.svg
  frontend/src/index.tsx
  frontend/src/mocks/dummy/rollingpapers.json
  frontend/src/mocks/handlers/messageHandlers.js
  frontend/src/pages/RollingpaperPage/components/Like.tsx
  frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
  frontend/src/pages/RollingpaperPage/hooks/useDeleteLiked.tsx
  frontend/src/pages/RollingpaperPage/hooks/useUpdateLiked.tsx
  frontend/src/types/apiRequest.ts
  frontend/src/types/index.ts
Labels: 프론트엔드, 기능, UI

#528 feature: 가입한 모임 목록 페이지 구현
  frontend/src/App.tsx
  frontend/src/pages/MainPage/components/MyTeamsSection.tsx
  frontend/src/pages/MyTeamPage/hooks/useReadMyTeams.tsx
  frontend/src/pages/MyTeamPage/index.tsx
Labels: 프론트엔드, UI

#536 fix: 롤링페이퍼 만들기 페이지에서 보이는 불필요한 스크롤바를 제거한다.
  frontend/src/pages/RollingpaperCreationPage/components/StepTitleWithLayout.tsx
Labels: 프론트엔드, 버그, UI

#535 feat: Header 로고와 메인페이지 Navigation UI를 수정한다.
  frontend/src/assets/images/logo-fill.png
  frontend/src/components/Header.tsx
  frontend/src/components/RoundButtonWithDescription.tsx
  frontend/src/pages/MainPage/components/NavigationButton.tsx
  frontend/src/pages/MainPage/index.tsx
Labels: 프론트엔드, 리팩토링, UI

#530 feat: 가입한 팀 조회시 최근 가입 순으로 정렬
  backend/src/main/java/com/woowacourse/naepyeon/repository/teamparticipation/TeamParticipationRepositoryImpl.java
Labels: 백엔드, 기능

#541 refactor: 롤링페이퍼 생성 플로우 UI를 개선한다.
  frontend/src/pages/RollingpaperCreationPage/components/RecipientBox.tsx
Labels: 프론트엔드, UI

#547 refactor: 모임 상세 페이지에서 초대하기, 모임 프로필 설정이 보이도록 한다.
  frontend/src/pages/TeamDetailPage/components/TeamDescriptionBox.tsx
Labels: 프론트엔드, 리팩토링, UI

#546 feat: 내가 가입한 팀 조회 페이징 역순
  backend/src/main/java/com/woowacourse/naepyeon/repository/teamparticipation/TeamParticipationRepositoryImpl.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java
Labels: 백엔드, 기능

#548 feat: 메세지 삭제지 메세지 좋아요 기록도 삭제
  backend/src/main/java/com/woowacourse/naepyeon/repository/messagelike/MessageLikeRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
Labels: 백엔드, 기능

#550 feat: 롤링페이퍼 조회 시 메시지 순서를 오래된 순에서 최신 순으로 변경한다
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
Labels: 백엔드, 리팩토링

#551 feature: 롤링페이퍼 내 메시지 정렬 순서를 변경한다.
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
Labels: 프론트엔드, UI

#555 fix: UI 오류를 해결한다.
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/components/Step1.tsx
Labels: 프론트엔드, 버그, UI

#557 feat: 나의 롤링페이퍼를 오래된 순에서 최신 순으로 변경한다
  backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryImpl.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
Labels: 백엔드, 버그, 기능

#559 chore: 0.5.1 버전을 배포한다.
  backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryImpl.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/components/Step1.tsx
Labels: 프론트엔드, 백엔드, 버그, 기능, UI

#567 feat: 메시지 삭제 전 confirm을 추가한다.
  frontend/src/pages/RollingpaperPage/hooks/useMessageBox.tsx
Labels: 프론트엔드, UI

#568 feat: 메시지 입력 시 Enter 한 번 만 가능하도록 구현
  frontend/src/pages/RollingpaperPage/hooks/useMessageForm.tsx
Labels: 프론트엔드, 리팩토링

#484 feat: 데이터베이스 이중화 기능을 구현한다.
  backend/docker/README.md
  backend/docker/docker-compose.yml
  backend/docker/replica/Dockerfile
  backend/docker/replica/my.cnf
  backend/docker/source/Dockerfile
  backend/docker/source/my.cnf
  backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java
  backend/src/main/java/com/woowacourse/naepyeon/support/db/DatabaseType.java
  backend/src/main/java/com/woowacourse/naepyeon/support/db/RoutingDataSource.java
  backend/src/main/resources/application-deploy.yml
  backend/src/main/resources/application-develop.yml
  backend/src/main/resources/application-flywayTest.yml
  backend/src/main/resources/application.yml
  backend/src/test/resources/application.yml
Labels: 백엔드, 인프라, 기능

#574 docs: 프론트엔드 기술스택 추가
  README.md
Labels: 프론트엔드, 문서

#582 feat: 웹 접근성을 개선한다
  frontend/src/components/IconButton.tsx
  frontend/src/components/PageTitleWithBackButton.tsx
  frontend/src/components/Snackbar.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/src/pages/RollingpaperPage/components/Like.tsx
  frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
  frontend/src/pages/RollingpaperPage/components/MessageColorPicker.tsx
  frontend/src/pages/RollingpaperPage/components/MessageForm.tsx
  frontend/src/pages/RollingpaperPage/hooks/useMessageForm.tsx
  frontend/src/pages/TeamCreationPage/index.tsx
Labels: 프론트엔드, 리팩토링

#569 fix: UserProfile에서 이름 수정 후 엔터를 눌렀을 때 새로고침 되는 버그를 해결한다.
  frontend/src/pages/MyPage/components/UserProfile.tsx
Labels: 프론트엔드, 버그, UI

#571 feat: 롤링페이퍼 정렬/필터링 기능을 구현한다.
  frontend/src/api/team.ts
  frontend/src/constants/index.ts
  frontend/src/mocks/handlers/rollingpaperHandlers.js
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
  frontend/src/pages/TeamDetailPage/hooks/useReadTeamRollingpaper.tsx
  frontend/src/types/apiRequest.ts
Labels: 프론트엔드, 기능

#583 fix: 사용자 안내 문구를 변경한다.
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/TeamJoinSection.tsx
Labels: 프론트엔드, 버그, UI

#572 feat: 알림 기능 UI를 구현한다.
  frontend/src/App.tsx
  frontend/src/assets/icons/bx-bell.svg
  frontend/src/components/Badge.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/IconButton.tsx
  frontend/src/components/PageTitle.tsx
  frontend/src/components/PageTitleWithBackButton.tsx
  frontend/src/components/stories/PageTitleWithBackButton.stories.jsx
  frontend/src/pages/NotificationPage/components/DeleteAllNotificationButton.tsx
  frontend/src/pages/NotificationPage/components/NotificationItem.tsx
  frontend/src/pages/NotificationPage/index.tsx
  frontend/src/pages/PolicyPage/index.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
  frontend/src/pages/TeamCreationPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperListItem.tsx
  frontend/src/styles/theme.ts
Labels: 프론트엔드, UI

#584 feat: 로딩 UI를 개선한다.
  frontend/src/App.tsx
  frontend/src/components/Loading.tsx
  frontend/src/components/stories/Dropdown.stories.jsx
  frontend/src/components/stories/Loading.stories.jsx
  frontend/src/components/stories/MyTeamCard.stories.jsx
  frontend/src/pages/GoogleRedirectPage/index.tsx
  frontend/src/pages/InvitePage/index.tsx
  frontend/src/pages/KakaoRedirectPage/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/MainPage/components/MyTeamsSection.tsx
  frontend/src/pages/MainPage/components/ReceivedRollingpapersSection.tsx
  frontend/src/pages/MyPage/components/MessageList.tsx
  frontend/src/pages/MyPage/components/RollingpaperList.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/MyTeamPage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/components/Step1.tsx
  frontend/src/pages/RollingpaperCreationPage/components/Step2.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
  frontend/src/pages/TeamDetailPage/index.tsx
  frontend/src/pages/TeamSearchPage/index.tsx
Labels: 프론트엔드, UI

#591 feat: 모임 상세 페이지 롤링페이퍼 empty state UI 구현
  frontend/src/assets/images/surprise-state.svg
  frontend/src/pages/TeamDetailPage/components/EmptyTeamRollingpaper.tsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
Labels: 프론트엔드, UI

#589 refactor: 롤링페이퍼 생성 페이지를 개선한다
  frontend/src/components/ControlDots.tsx
  frontend/src/components/ProgressBar.tsx
  frontend/src/components/stories/Loading.stories.jsx
  frontend/src/components/stories/ProgressBar.stories.jsx
  frontend/src/pages/RollingpaperCreationPage/components/RecipientBox.tsx
  frontend/src/pages/RollingpaperCreationPage/components/Step1.tsx
  frontend/src/pages/RollingpaperCreationPage/components/Step2.tsx
  frontend/src/pages/RollingpaperCreationPage/components/Step3.tsx
  frontend/src/pages/RollingpaperCreationPage/components/StepLayout.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useSteps.tsx
  frontend/src/pages/RollingpaperCreationPage/index.tsx
Labels: 프론트엔드, 리팩토링, UI

#593 feat: 실시간 알림 기능을 구현한다.
  backend/build.gradle
  backend/src/docs/asciidoc/errorCodes.adoc
  backend/src/docs/asciidoc/notifications.adoc
  backend/src/main/java/com/woowacourse/naepyeon/config/AuthenticationPrincipalConfig.java
  backend/src/main/java/com/woowacourse/naepyeon/config/RedisConfig.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/NotificationController.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/notification/ContentType.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/notification/Notification.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidRedisMessageException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/NotFoundNotificationException.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/notification/NotificationRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/notification/NotificationRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/notification/NotificationRepositoryImpl.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/NotificationService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/NotificationResponseDto.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/NotificationsResponseDto.java
  backend/src/main/java/com/woowacourse/naepyeon/service/event/RollingpaperAndTeamIdEvent.java
  backend/src/main/java/com/woowacourse/naepyeon/service/event/RollingpaperEvent.java
  backend/src/main/resources/application-deploy.yml
  backend/src/main/resources/application-develop.yml
  backend/src/main/resources/application-flywayTest.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/V0.5.2__notification.sql
  backend/src/test/java/com/woowacourse/naepyeon/document/NotificationControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/NotificationRepositoryTest.java
  backend/src/test/resources/application.yml
Labels: 백엔드, 기능, 중요

#598 fix: 누락된 롤링페이퍼 생성 버튼 추가
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
  frontend/src/pages/TeamDetailPage/index.tsx
Labels: 프론트엔드, 버그, UI

#602 fix: Paging의 스타일을 수정한다
  frontend/src/components/Paging.tsx
Labels: 프론트엔드, UI

#603 refactor: 본인이 작성한 메시지, 롤링페이퍼에는 알림을 받지 않게 수정
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/NotificationService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/event/RollingpaperAndAuthorIdEvent.java
  backend/src/main/java/com/woowacourse/naepyeon/service/event/RollingpaperAndTeamIdAndAuthorIdEvent.java
Labels: 백엔드, 리팩토링

#606 fix: 멤버 롤링페이퍼 생성 시 화면 이동하도록 한다
  frontend/src/pages/RollingpaperCreationPage/hooks/useCreateMemberRolliingpaper.tsx
Labels: 프론트엔드, 버그

#608 refactor: 서버 요청 데이터가 없는 경우 Loading UI를 보여준다
  frontend/src/pages/MainPage/components/MyTeamsSection.tsx
  frontend/src/pages/MainPage/components/ReceivedRollingpapersSection.tsx
  frontend/src/pages/MyPage/components/MessageList.tsx
  frontend/src/pages/MyPage/components/RollingpaperList.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/MyTeamPage/index.tsx
  frontend/src/pages/NotificationPage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/components/Step2.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
  frontend/src/pages/TeamDetailPage/index.tsx
  frontend/src/pages/TeamSearchPage/index.tsx
Labels: 프론트엔드, UI

#609 refactor: 모임 검색하기 페이지 UI를 개선한다.
  frontend/src/pages/TeamSearchPage/index.tsx
Labels: 프론트엔드, UI

#613 fix: 아이폰에서 버튼 색상이 파란색으로 보이는 문제를 해결
  frontend/src/styles/reset.ts
Labels: 프론트엔드, 버그, UI

#616 fix: 모바일 UI 오류를 해결한다
  frontend/src/components/LabeledSwitch.tsx
  frontend/src/components/Modal.tsx
  frontend/src/pages/TeamDetailPage/components/InviteModal.tsx
Labels: 프론트엔드, 버그, UI

#618 fix: 롤링페이퍼 만들기 페이지에서 불필요한 Loading 컴포넌트가 보이는 버그를 해결한다.
  frontend/src/pages/RollingpaperCreationPage/components/Step2.tsx
Labels: 프론트엔드, 버그, UI

#621 fix: ios 롤링페이퍼 만들기 progressBar 오류 수정
  frontend/src/pages/RollingpaperCreationPage/hooks/useSteps.tsx
Labels: 프론트엔드, 버그, UI

#623 fix: 알림 관련 UI를 개선한다.
  frontend/src/components/Badge.tsx
  frontend/src/mocks/dummy/notifications.json
  frontend/src/pages/NotificationPage/index.tsx
Labels: 프론트엔드, 버그, UI

#625 fix: accessToken 만료 시간을 늘린다.
  frontend/src/constants/index.ts
Labels: 프론트엔드, 기능

#628 chore: front 개발환경 개선
  .github/workflows/ci-frontend.yml
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/components/AutoCompleteInput.tsx
  frontend/src/components/ErrorBoundary.tsx
  frontend/src/pages/MyPage/components/MessageList.tsx
  frontend/src/pages/MyPage/components/RollingpaperList.tsx
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
  frontend/yarn.lock
Labels: 프론트엔드, 설정
