Repository woowacourse-teams/2022-nae-pyeon, pull requests merged in 2022-09, with the labels that each got.

#411 test: `AfterPropertiesSet`을 이용한 DB cleaner 클래스를 만들어 `@DirtiesContext` 제거
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/support/DatabaseCleaner.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MemberServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 리팩토링, 테스트

#430 refactor: font preload 및 로드 시 시스템 글꼴 일시적 표시 추가
  frontend/public/index.html
  frontend/src/styles/font.ts
Labels: 프론트엔드, 리팩토링

#431 refactor: Oauth 로그인 플랫폼 아이콘 파일 변경
  frontend/src/assets/images/logo-google.png
  frontend/src/assets/images/logo-kakao.png
  frontend/src/assets/images/logo-naver.png
Labels: 프론트엔드, 리팩토링

#420 [BE] Repository 추상화 계층을 변경한다
  backend/src/docs/asciidoc/rollingpapers.adoc
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaMemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaMessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaRollingpaperRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamParticipationRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaTeamRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/MemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/MessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/RollingpaperRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamParticipationRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/MemberJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/MessageJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/RollingpaperJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamParticipationJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MemberService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 리팩토링

#405 refactor: restDocs json파일 삭제 후 objectMapper로 대체한다.
  backend/src/docs/asciidoc/errorCodes.adoc
  backend/src/docs/asciidoc/rollingpapers.adoc
  backend/src/test/java/com/woowacourse/naepyeon/document/AuthControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/MemberControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/RollingpaperControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
  backend/src/test/resources/json/auth/login.json
  backend/src/test/resources/json/members/member-create.json
  backend/src/test/resources/json/members/member-update.json
  backend/src/test/resources/json/rollingpapers/rollingpaper-update.json
Labels: 백엔드, 문서, 리팩토링

#422 feat: 메시지 폼 관련 오류를 해결한다.
  frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
  frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
Labels: 프론트엔드, 리팩토링

#423 feat: 모임 프로필 설정 시 기존 모임 닉네임을 보여준다
  frontend/src/api/team.ts
  frontend/src/hooks/useInput.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
Labels: 프론트엔드, 기능

#424 refactor: 모임 추가하기 페이지 개선
  frontend/src/components/LabeledInput.tsx
  frontend/src/components/LabeledTextArea.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/TeamCreationPage/hooks/useTeamCreationForm.tsx
  frontend/src/pages/TeamCreationPage/index.tsx
Labels: 프론트엔드, 리팩토링

#425 refactor: MessageForm 추가될 때 메시지 정렬 방식 변경
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
  frontend/src/pages/RollingpaperPage/hooks/useSliceMessageList.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
Labels: 프론트엔드, 리팩토링

#441 chore: package, webpack, tsconfig 설정 파일을 변경
  .github/workflows/ci-frontend.yml
  .gitignore
  frontend/package.json
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 프론트엔드, 리팩토링

#444 refactor: 타입스크립트 컨벤션에 맞게 수정한다.
  frontend/src/api/index.ts
  frontend/src/api/kakaoOauth.ts
  frontend/src/api/member.ts
  frontend/src/api/message.ts
  frontend/src/api/rollingpaper.ts
  frontend/src/api/team.ts
  frontend/src/constants/index.ts
  frontend/src/hooks/useAutoLogin.tsx
  frontend/src/pages/InvitePage/hooks/useCheckLogin.tsx
  frontend/src/pages/InvitePage/hooks/useJoinTeamWithInviteToken.tsx
  frontend/src/pages/InvitePage/hooks/useTeamDetailWithInviteToken.tsx
  frontend/src/pages/KakaoRedirectPage/index.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/MyPage/components/MessageList.tsx
  frontend/src/pages/MyPage/components/RollingpaperList.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/components/RecipientBox.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useReadTeamMembers.tsx
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
  frontend/src/pages/TeamCreationPage/hooks/useCreateTeam.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
  frontend/src/pages/TeamDetailPage/hooks/useCreateInviteLink.tsx
  frontend/src/pages/TeamDetailPage/index.tsx
  frontend/src/pages/TeamSearchPage/index.tsx
  frontend/src/types/api.ts
  frontend/src/types/apiRequest.ts
  frontend/src/types/apiResponse.ts
  frontend/src/types/index.ts
  frontend/src/types/oauth.ts
Labels: 프론트엔드, 리팩토링

#453 chore: 커넥션 풀 사이즈 분리
  backend/src/main/resources/application-develop.yml
Labels: 백엔드, 설정

#438 refactor: Http 요청 로깅 위치를 preHandle로 변경
  backend/src/main/java/com/woowacourse/naepyeon/config/logging/CustomCachingRequestWrapper.java
  backend/src/main/java/com/woowacourse/naepyeon/config/logging/LoggingInterceptor.java
  backend/src/main/java/com/woowacourse/naepyeon/config/logging/RequestBodyWrappingFilter.java
  backend/src/main/java/com/woowacourse/naepyeon/support/invitetoken/aes/Aes256InviteTokenProvider.java
  backend/src/main/resources/application-flywayTest.yml
  backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
Labels: 백엔드, 리팩토링

#448 feat: google oauth 구현
  frontend/src/App.tsx
  frontend/src/api/googleOauth.ts
  frontend/src/constants/index.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/memberHandlers.js
  frontend/src/pages/GoogleRedirectPage/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/types/apiRequest.ts
Labels: 프론트엔드, 기능

#447 feat: 구글 OAuth기능을 구현한다.
  backend/src/docs/asciidoc/auth.adoc
  backend/src/docs/asciidoc/errorCodes.adoc
  backend/src/main/java/com/woowacourse/naepyeon/controller/auth/AuthController.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/GoogleAuthorizationException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/GoogleResourceException.java
  backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
  backend/src/main/java/com/woowacourse/naepyeon/support/oauth/PlatformUserProvider.java
  backend/src/main/java/com/woowacourse/naepyeon/support/oauth/dto/AccessTokenResponse.java
  backend/src/main/java/com/woowacourse/naepyeon/support/oauth/dto/GoogleAccessTokenResponse.java
  backend/src/main/java/com/woowacourse/naepyeon/support/oauth/dto/GoogleUserResponse.java
  backend/src/main/java/com/woowacourse/naepyeon/support/oauth/dto/KakaoUserResponse.java
  backend/src/main/java/com/woowacourse/naepyeon/support/oauth/google/GooglePlatformUserProvider.java
  backend/src/main/java/com/woowacourse/naepyeon/support/oauth/kakao/KakaoPlatformUserProvider.java
  backend/src/main/resources/application-deploy.yml
  backend/src/main/resources/application-develop.yml
  backend/src/main/resources/application-flywayTest.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/AuthControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
  backend/src/test/resources/application.yml
Labels: 백엔드, 기능

#460 refactor: tsconfig, webpack loader, devtool 변경
  frontend/babel.config.js
  frontend/jest.config.js
  frontend/tsconfig.json
  frontend/webpack.dev.js
Labels: 프론트엔드, 설정

#442 feat: queryDSL을 적용한다
  backend/build.gradle
  backend/src/main/java/com/woowacourse/naepyeon/config/QueryDslConfig.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/MemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/MessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/RollingpaperRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/TeamParticipationRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/member/MemberRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/member/MemberRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/member/MemberRepositoryImpl.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryImpl.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/team/TeamRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/teamparticipation/TeamParticipationRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/teamparticipation/TeamParticipationRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/teamparticipation/TeamParticipationRepositoryImpl.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MemberService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MemberRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamParticipationRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/TeamRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 리팩토링

#464 feat: develop.yml에서 flyway enabled true로 변경
  backend/src/main/resources/application-develop.yml
Labels: 백엔드, 인프라, 설정

#468 chore: 개발서버 설정파일 수정
  backend/src/main/resources/application-develop.yml
Labels: 백엔드, 설정

#467 feat: Google 로그인 버튼 기능을 준비 중으로 변경
  frontend/public/index.html
  frontend/src/pages/LoginPage/index.tsx
Labels: 프론트엔드, 기능

#454 feat: API 커스텀 훅을 분리하고 에러 바운더리 설정을 추가
  frontend/src/App.tsx
  frontend/src/components/ErrorBoundary.tsx
  frontend/src/hooks/useAutoLogin.tsx
  frontend/src/pages/InvitePage/hooks/useCreateTeamWithInviteToken.tsx
  frontend/src/pages/InvitePage/hooks/useJoinTeamWithInviteToken.tsx
  frontend/src/pages/InvitePage/hooks/useReadTeamDetailWithInviteToken.tsx
  frontend/src/pages/InvitePage/hooks/useTeamDetailWithInviteToken.tsx
  frontend/src/pages/InvitePage/index.tsx
  frontend/src/pages/KakaoRedirectPage/hooks/useCreateKakaoOauthLogin.tsx
  frontend/src/pages/KakaoRedirectPage/index.tsx
  frontend/src/pages/MyPage/components/MessageList.tsx
  frontend/src/pages/MyPage/components/RollingpaperList.tsx
  frontend/src/pages/MyPage/components/UserProfile.tsx
  frontend/src/pages/MyPage/hooks/useReadReceivedRollingpapers.tsx
  frontend/src/pages/MyPage/hooks/useReadSentMessages.tsx
  frontend/src/pages/MyPage/hooks/useReadUserProfile.tsx
  frontend/src/pages/MyPage/hooks/useUpdateUserProfile.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperCreationPage/components/TeamRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useCreateMemberRolliingpaper.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useCreateTeamRollingpaper.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useReadTeamMembers.tsx
  frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
  frontend/src/pages/RollingpaperPage/hooks/useCreateMessage.tsx
  frontend/src/pages/RollingpaperPage/hooks/useDeleteMessage.tsx
  frontend/src/pages/RollingpaperPage/hooks/useReadRollingpaper.tsx
  frontend/src/pages/RollingpaperPage/hooks/useUpdateMessage.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
  frontend/src/pages/TeamCreationPage/hooks/useCreateTeam.tsx
  frontend/src/pages/TeamDetailPage/components/InviteModal.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameCreateModalForm.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
  frontend/src/pages/TeamDetailPage/hooks/useCreateInviteLink.tsx
  frontend/src/pages/TeamDetailPage/hooks/useCreateTeamMember.tsx
  frontend/src/pages/TeamDetailPage/hooks/useReadTeamDetail.tsx
  frontend/src/pages/TeamDetailPage/hooks/useReadTeamNickname.tsx
  frontend/src/pages/TeamDetailPage/hooks/useReadTeamRollingpaper.tsx
  frontend/src/pages/TeamDetailPage/hooks/useUpdateTeamNickname.tsx
  frontend/src/pages/TeamDetailPage/index.tsx
  frontend/src/types/api.ts
  frontend/src/types/apiResponse.ts
Labels: 프론트엔드, 리팩토링

#449 feat: DB에 인덱스를 적용한다
  backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Team.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Rollingpaper.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/V0.4.2__db_index.sql
  backend/src/main/resources/log4j2.yml
Labels: 백엔드, 리팩토링, 설정, 중요

#474 fix: 작성한 메시지 개수를 해당페이지 개수로만 가져오는 버그 수정
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
Labels: 백엔드, 버그

#477 fix: 작성한 메시지 개수를 해당페이지 개수로만 가져오는 버그 수정 - 리팩터링 필요
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
Labels: 백엔드, 버그

#478 fix: 작성한 메시지 개수를 해당페이지 개수로만 가져오는 버그 수정 - 리팩터링 필요
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
Labels: 백엔드, 버그

#479 fix: 잘못된 querydsl JPQL로 임시로 변환
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
Labels: 백엔드, 버그

#480 refactor: requestApi 함수를 수정한다.
  frontend/src/api/googleOauth.ts
  frontend/src/api/index.ts
  frontend/src/api/kakaoOauth.ts
  frontend/src/api/member.ts
  frontend/src/api/message.ts
  frontend/src/api/rollingpaper.ts
  frontend/src/api/team.ts
Labels: 프론트엔드, 리팩토링

#481 feat: error page 수정
  frontend/src/App.tsx
  frontend/src/pages/ErrorPage/index.tsx
Labels: 프론트엔드, 리팩토링

#483 fix: 롤링페이퍼 생성 페이지의 받는 사람 자동완성 기능 오류를 해결한다.
  frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useReadTeamMembers.tsx
Labels: 프론트엔드, 버그

#486 feat: v0.4.3을 배포한다.
  backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Team.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Rollingpaper.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryCustom.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/V0.4.2__db_index.sql
  backend/src/main/resources/log4j2.yml
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  frontend/src/App.tsx
  frontend/src/api/googleOauth.ts
  frontend/src/api/index.ts
  frontend/src/api/kakaoOauth.ts
  frontend/src/api/member.ts
  frontend/src/api/message.ts
  frontend/src/api/rollingpaper.ts
  frontend/src/api/team.ts
  frontend/src/pages/ErrorPage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useReadTeamMembers.tsx
Labels: 프론트엔드, 백엔드
