Repository woowacourse-teams/2022-nae-pyeon, pull requests merged in 2022-08, with the labels that each got.

#239 refactor: useQuery에 사용하는 query keys 업데이트
  frontend/src/pages/RollingpaperCreationPage/index.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
  frontend/src/pages/TeamDetailPage/index.tsx
Labels: 프론트엔드, 리팩토링

#235 feat: Kakao Oauth 기능 구현
  frontend/src/App.tsx
  frontend/src/api/kakaoOauth.ts
  frontend/src/constants/index.ts
  frontend/src/mocks/handlers/memberHandlers.js
  frontend/src/pages/KakaoRedirectPage/index.tsx
  frontend/src/pages/LoginPage/components/Logo.tsx
  frontend/src/pages/LoginPage/components/SocialLoginButton.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/SignUpPage/index.tsx
  frontend/src/types/oauth.ts
  frontend/src/util/cookie.ts
Labels: 프론트엔드, 기능, UI

#232 feat: header sticky 추가
  frontend/src/components/Header.tsx
Labels: 프론트엔드, UI

#234 feat: 마이페이지에서 내가 받은 롤링페이퍼 목록 api 기능 구현
  backend/src/main/java/com/woowacourse/naepyeon/controller/MemberController.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaRollingpaperRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/RollingpaperRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/RollingpaperJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/ReceivedRollingpaperResponseDto.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/ReceivedRollingpapersResponseDto.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/RollingpaperRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
Labels: 백엔드, 기능

#244 test: 스토리북 설정 변경 및 스토리 보완
  frontend/.storybook/preview.js
  frontend/src/components/stories/AutoCompleteInput.stories.jsx
  frontend/src/components/stories/Button.stories.jsx
  frontend/src/components/stories/Header.stories.jsx
  frontend/src/components/stories/IconButton.stories.jsx
  frontend/src/components/stories/LabeledInput.stories.jsx
  frontend/src/components/stories/LabeledRadio.stories.jsx
  frontend/src/components/stories/LabeledTextArea.stories.jsx
  frontend/src/components/stories/LineButton.stories.jsx
  frontend/src/components/stories/Modal.stories.jsx
  frontend/src/components/stories/PageTitle.stories.jsx
  frontend/src/components/stories/PageTitleWithBackButton.stories.jsx
  frontend/src/components/stories/Paging.stories.jsx
  frontend/src/components/stories/SearchInput.stories.jsx
  frontend/src/components/stories/UnderlineInput.stories.jsx
  frontend/src/pages/LoginPage/components/PasswordInput.stories.jsx
  frontend/src/pages/LoginPage/components/SocialLoginButton.stories.jsx
  frontend/src/pages/MainPage/components/MyTeamCard.stories.jsx
  frontend/src/pages/MainPage/components/TeamCreateButton.stories.jsx
  frontend/src/pages/MyPage/components/MessageCard.stories.jsx
  frontend/src/pages/MyPage/components/MyPageTab.stories.jsx
  frontend/src/pages/MyPage/components/RollingpaperCard.stories.jsx
  frontend/src/pages/MyPage/components/UserProfile.stories.jsx
  frontend/src/pages/RollingpaperPage/components/LetterPaper.stories.jsx
  frontend/src/pages/RollingpaperPage/components/MessageColorPicker.stories.jsx
  frontend/src/pages/RollingpaperPage/components/MessageForm.stories.jsx
  frontend/src/pages/RollingpaperPage/components/MessageTextArea.stories.jsx
  frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.stories.jsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.stories.jsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperListItem.stories.jsx
  frontend/src/pages/TeamDetailPage/components/TeamJoinModalForm.stories.jsx
  frontend/src/pages/TeamDetailPage/components/TeamJoinSection.stories.jsx
  frontend/src/pages/TeamSearchPage/components/SearchResultItem.stories.jsx
Labels: 프론트엔드, 테스트

#250 feat: 롤링페이퍼 생성 폼 유효성 검사 구현
  frontend/src/constants/index.ts
  frontend/src/pages/RollingpaperCreationPage/index.tsx
Labels: 프론트엔드, UI

#236 feat: 팀 상세보기 페이지 더보기 구현
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/api/index.ts
  frontend/src/assets/icons/bx-dots-horizontal-rounded.svg
  frontend/src/components/Dropdown.tsx
  frontend/src/components/Modal.tsx
  frontend/src/components/stories/MoreDropdown.stories.jsx
  frontend/src/context/UserContext.tsx
  frontend/src/mocks/handlers/teamHandlers.js
  frontend/src/pages/KakaoRedirectPage/index.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/MyPage/components/UserProfile.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/index.tsx
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
  frontend/src/pages/TeamCreationPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
  frontend/src/pages/TeamDetailPage/components/TeamDescriptionBox.tsx
  frontend/src/pages/TeamDetailPage/components/TeamJoinModalForm.stories.jsx
  frontend/src/pages/TeamDetailPage/components/TeamJoinModalForm.tsx
  frontend/src/pages/TeamDetailPage/components/TeamJoinSection.tsx
  frontend/src/pages/TeamDetailPage/components/TeamNicknameModalForm.tsx
  frontend/src/pages/TeamDetailPage/index.tsx
  frontend/src/pages/TeamSearchPage/index.tsx
Labels: 프론트엔드, 기능, UI

#246 feat: 메시지 수정 오류 해결
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx
Labels: 프론트엔드, 버그

#257 fix: UserContext의 내 정보 조회 요청 URL 수정
  frontend/src/context/UserContext.tsx
Labels: 프론트엔드, 버그

#251 feat: Pagination API 명세와 관련된 컴포넌트 로직 수정
  frontend/src/components/Paging.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/TeamSearchPage/index.tsx
Labels: 프론트엔드, 기능

#237 feat: 마이페이지에서 내가 작성한 메시지 목록 api 기능 구현
  backend/src/main/java/com/woowacourse/naepyeon/controller/MemberController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/MessageController.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaMessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/MessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/MessageJpaDao.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/WrittenMessageResponseDto.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/WrittenMessagesResponseDto.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/RollingpaperAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
Labels: 백엔드, 기능

#264 feat: 롤링페이퍼 메시지 정렬 순서 변경
  frontend/src/pages/RollingpaperPage/index.tsx
Labels: 프론트엔드, UI

#262 feat: Header z index 수정
  frontend/src/components/Dropdown.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Modal.tsx
Labels: 프론트엔드, 버그, UI

#263 feat: 카카오 로그인 API 명세 변경에 따라 관련 로직 변경
  frontend/src/api/kakaoOauth.ts
  frontend/src/mocks/handlers/memberHandlers.js
  frontend/src/pages/KakaoRedirectPage/index.tsx
  frontend/src/types/oauth.ts
Labels: 프론트엔드, 리팩토링

#261 feat: 메인 페이지에 Infinte scroll을 추가한다
  frontend/src/api/team.ts
  frontend/src/mocks/dummy/myTeams.json
  frontend/src/mocks/handlers/teamHandlers.js
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/TeamSearchPage/index.tsx
Labels: 프론트엔드, 기능, UI

#265 feat: 메인 페이지의 가입한 모임 목록 empty state UI 추가
  frontend/src/assets/images/empty_state.svg
  frontend/src/pages/MainPage/components/EmptyMyTeamList.tsx
  frontend/src/pages/MainPage/index.tsx
Labels: 프론트엔드, UI

#270 feat: myTeam type 추가로 오류 해결
  frontend/src/pages/MainPage/index.tsx
Labels: 프론트엔드, 버그

#277 feat: message 수정 요청에 색상 추가
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
Labels: 프론트엔드, 버그

#279 feat: 네이버, 구글 로그인 버튼 UI 구현 및 로그인 페이지에 추가
  frontend/src/assets/images/logo-google.png
  frontend/src/assets/images/logo-kakao.png
  frontend/src/assets/images/logo-naver.png
  frontend/src/constants/index.ts
  frontend/src/pages/LoginPage/components/SocialLoginButton.tsx
  frontend/src/pages/LoginPage/index.tsx
Labels: 프론트엔드, 리팩토링, UI

#280 fix: 페이지네이션이 적용된 API 요청에서 발생하는 오류 해결
  frontend/src/api/team.ts
  frontend/src/pages/TeamSearchPage/index.tsx
Labels: 프론트엔드, 버그

#281 fix: MyPage API 로직의 placeholderData 제거
  frontend/src/pages/MyPage/index.tsx
Labels: 프론트엔드, 버그

#283 feat: MyPage styling 수정
  frontend/src/mocks/dummy/sentMessages.json
  frontend/src/mocks/handlers/memberHandlers.js
  frontend/src/pages/MyPage/components/MessageList.tsx
  frontend/src/pages/MyPage/components/MessageListItem.stories.jsx
  frontend/src/pages/MyPage/components/MessageListItem.tsx
  frontend/src/pages/MyPage/components/RollingpaperListItem.stories.jsx
  frontend/src/pages/MyPage/components/RollingpaperListItem.tsx
  frontend/src/pages/MyPage/index.tsx
Labels: 프론트엔드, UI

#286 refactor: 마이페이지 내 API 요청의 위치 변경
  frontend/src/api/member.ts
  frontend/src/constants/index.ts
  frontend/src/pages/MyPage/components/MessageList.tsx
  frontend/src/pages/MyPage/components/RollingpaperList.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 리팩토링

#268 feat: MessageForm 컴포넌트의 작성 취소 아이콘을 변경하고 수정시 글자수가 나오도록 수정
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/src/pages/RollingpaperPage/components/MessageForm.tsx
  frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
Labels: 프론트엔드, 기능, UI

#288 fix: 반응형 UI 오류 수정
  frontend/src/mocks/handlers/teamHandlers.js
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/MainPage/components/MyTeamCard.tsx
Labels: 프론트엔드, 버그, UI

#296 feat: restDocs 테스트 코드 추가 및 수정
  backend/src/docs/asciidoc/auth.adoc
  backend/src/docs/asciidoc/members.adoc
  backend/src/docs/asciidoc/messages.adoc
  backend/src/docs/asciidoc/rollingpapers.adoc
  backend/src/docs/asciidoc/teams.adoc
  backend/src/test/java/com/woowacourse/naepyeon/document/AuthControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/MemberControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/MessageControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/RollingpaperControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/TeamControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
  backend/src/test/resources/json/messages/message-create.json
  backend/src/test/resources/json/messages/message-update.json
  backend/src/test/resources/json/teams/update-my-info.json
Labels: 백엔드, 문서, 리팩토링

#290 feat: 유저 정보가 변경되면 변경된 정보를 refetch
  frontend/src/pages/MyPage/components/UserProfile.tsx
Labels: 프론트엔드, 기능, 리팩토링

#289 feat: mypage에 empty state를 추가한다
  frontend/src/assets/images/empty-state.svg
  frontend/src/assets/images/empty_state.svg
  frontend/src/pages/MainPage/components/EmptyMyTeamList.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/MyPage/components/MessageList.tsx
  frontend/src/pages/MyPage/components/RollingpaperList.tsx
  frontend/src/pages/MyPage/index.tsx
Labels: 프론트엔드, UI

#302 feat: 검색창 오류 해결
  frontend/src/pages/TeamSearchPage/index.tsx
Labels: 프론트엔드, 버그

#303 feat: 메시지 삭제 confirm 추가
  frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx
Labels: 프론트엔드, 기능

#301 feat: 명세에 맞도록 사용자 이름과 모임 닉네임 조건을 수정
  frontend/src/constants/index.ts
  frontend/src/pages/MyPage/components/UserProfile.tsx
  frontend/src/pages/RollingpaperCreationPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/TeamNicknameModalForm.tsx
Labels: 프론트엔드, 기능, 리팩토링

#308 feat: 긴 닉네임이 메시지에 나올 수 있도록 style 수정
  frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx
Labels: 프론트엔드, UI

#309 feat: 전체 모임 검색에서 검색 결과가 없을 시 보여줄 empty state UI를 구현
  frontend/src/mocks/handlers/teamHandlers.js
  frontend/src/pages/TeamSearchPage/index.tsx
Labels: 프론트엔드, UI

#313 test: E2E 테스트 환경 설정
  frontend/cypress.config.ts
  frontend/cypress/e2e/MainPage.cy.js
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/package.json
  frontend/src/index.tsx
  frontend/src/mocks/browser.js
Labels: 프론트엔드, 설정, 테스트

#318 feat: 개발 설정과 프로덕션 설정을 나누고 테이블 및 제약조건 선언을 초기화한다.
  backend/.gitignore
  backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java
  backend/src/main/resources/application-flywayTest.yml
  backend/src/main/resources/db/migration/V0.3.0__init.sql
  backend/src/main/resources/db/migration/V1__init.sql
  backend/src/main/resources/db/migration/V2__add_baseEntity.sql
  backend/src/main/resources/db/migration/V3__add_message_color.sql
  backend/src/main/resources/db/migration/V4__update_member.sql
  backend/src/main/resources/log4j2.yml
Labels: 백엔드, 인프라, 설정

#320 fix: 초기 사용자 정보 요청 API 호출 순서 오류를 수정
  frontend/src/App.tsx
  frontend/src/api/index.ts
  frontend/src/api/member.ts
  frontend/src/components/RequireLogin.tsx
  frontend/src/components/RequireLogout.tsx
  frontend/src/context/UserContext.tsx
  frontend/src/hooks/useAutoLogin.tsx
  frontend/src/index.tsx
  frontend/src/util/cookie.ts
Labels: 프론트엔드, 버그, 리팩토링

#325 feat: 초대 링크 리다이렉트 페이지, 초대 링크, 비공개 모임 추가 UI를 구현
  frontend/src/App.tsx
  frontend/src/assets/icons/bx-copy.svg
  frontend/src/components/AutoCompleteInput.tsx
  frontend/src/components/LabeledInput.tsx
  frontend/src/components/LabeledRadio.tsx
  frontend/src/components/LabeledTextArea.tsx
  frontend/src/components/Snackbar.tsx
  frontend/src/components/Switch.tsx
  frontend/src/pages/InvitePage/components/TeamDescriptionBox.tsx
  frontend/src/pages/InvitePage/index.tsx
  frontend/src/pages/MainPage/components/MyTeamCard.tsx
  frontend/src/pages/TeamCreationPage/components/LabeledSwitch.stories.jsx
  frontend/src/pages/TeamCreationPage/components/LabeledSwitch.tsx
  frontend/src/pages/TeamCreationPage/hooks/useSwitch.tsx
  frontend/src/pages/TeamCreationPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/InviteModal.tsx
  frontend/src/pages/TeamDetailPage/components/TeamDescriptionBox.tsx
  frontend/src/util/copyClipboard.ts
Labels: 프론트엔드, UI

#328 feat: 공통 컴포넌트의 비즈니스 로직을 커스텀훅으로 분리한다
  frontend/src/components/AutoCompleteInput.tsx
  frontend/src/components/Dropdown.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/LabeledInput.tsx
  frontend/src/components/Paging.tsx
  frontend/src/components/UnderlineInput.tsx
  frontend/src/hooks/useAutoCompleteInput.tsx
  frontend/src/hooks/useDropdown.tsx
  frontend/src/hooks/useInput.tsx
  frontend/src/hooks/useModal.tsx
  frontend/src/hooks/usePaging.tsx
  frontend/src/pages/InvitePage/index.tsx
  frontend/src/pages/LoginPage/components/PasswordInput.stories.jsx
  frontend/src/pages/LoginPage/components/PasswordInput.tsx
  frontend/src/pages/MyPage/components/MessageList.tsx
  frontend/src/pages/MyPage/components/RollingpaperList.tsx
  frontend/src/pages/MyPage/components/UserProfile.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/index.tsx
  frontend/src/pages/TeamCreationPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameCreateModalForm.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
  frontend/src/pages/TeamDetailPage/components/TeamDescriptionBox.tsx
  frontend/src/pages/TeamDetailPage/components/TeamJoinSection.tsx
Labels: 프론트엔드, 리팩토링

#329 feat: 익명 메시지, 비밀 메시지 작성 UI 구현
  frontend/src/components/CheckBox.tsx
  frontend/src/components/IconButton.tsx
  frontend/src/components/LabeledCheckBox.tsx
  frontend/src/components/stories/CheckBox.stories.jsx
  frontend/src/components/stories/Dropdown.stories.jsx
  frontend/src/components/stories/LabeledCheckBox.stories.jsx
  frontend/src/hooks/useCheckBox.tsx
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/src/pages/RollingpaperPage/components/MessageColorPicker.tsx
  frontend/src/pages/RollingpaperPage/components/MessageForm.tsx
  frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
  frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx
Labels: 프론트엔드, UI

#331 feat: 메시지 익명, 비밀 기능을 추가한다.
  backend/src/main/java/com/woowacourse/naepyeon/controller/MessageController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MessageRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Rollingpaper.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/MessageRequestDto.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/MessageResponseDto.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MessageAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/MessageTest.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/RollingpaperTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
Labels: 백엔드, 기능

#335 feat: API 관련 코드를 분리
  frontend/src/api/member.ts
  frontend/src/api/message.ts
  frontend/src/api/rollingpaper.ts
  frontend/src/api/team.ts
  frontend/src/hooks/useAutoLogin.tsx
  frontend/src/hooks/useParamValidate.tsx
  frontend/src/pages/MyPage/components/UserProfile.tsx
  frontend/src/pages/MyPage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/index.tsx
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
  frontend/src/pages/TeamCreationPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameCreateModalForm.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
  frontend/src/pages/TeamDetailPage/components/TeamDescriptionBox.tsx
  frontend/src/pages/TeamDetailPage/index.tsx
  frontend/src/pages/TeamSearchPage/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 리팩토링

#338 feat: 비밀글(비밀 메시지) UI 구현
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx
  frontend/src/pages/RollingpaperPage/components/SecretMessage.stories.jsx
  frontend/src/pages/RollingpaperPage/components/SecretMessage.tsx
Labels: 프론트엔드, UI

#336 feat: 초대코드 관련 기능을 구현한다.
  backend/.gitignore
  backend/src/docs/asciidoc/errorCodes.adoc
  backend/src/docs/asciidoc/teams.adoc
  backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/InviteJoinRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/InviteTokenResponse.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidMemberUsernameException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InviteTokenInvalidExpiredException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InviteTokenInvalidFormException.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InviteTokenInvalidSecretKeyException.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/main/java/com/woowacourse/naepyeon/support/InviteTokenProvider.java
  backend/src/main/resources/application-deploy.yml
  backend/src/main/resources/application-flywayTest.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/TeamControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/support/InviteTokenProviderTest.java
  backend/src/test/resources/application.yml
Labels: 백엔드, 기능

#342 feat: 모임 관련 API 및 로직에 공개/비공개 여부 추가
  frontend/src/api/team.ts
  frontend/src/components/LabeledSwitch.tsx
  frontend/src/components/LabeledTextArea.tsx
  frontend/src/components/stories/LabeledSwitch.stories.jsx
  frontend/src/hooks/useSwitch.tsx
  frontend/src/hooks/useTextArea.tsx
  frontend/src/mocks/dummy/totalTeams.json
  frontend/src/mocks/handlers/teamHandlers.js
  frontend/src/pages/TeamCreationPage/hooks/useCreateTeam.tsx
  frontend/src/pages/TeamCreationPage/hooks/useTeamCreationForm.tsx
  frontend/src/pages/TeamCreationPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/TeamDescriptionBox.tsx
  frontend/src/pages/TeamDetailPage/components/TeamJoinSection.tsx
  frontend/src/pages/TeamDetailPage/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 기능, UI

#352 feat: 초대 링크 관련 기능 구현
  frontend/src/App.tsx
  frontend/src/api/team.ts
  frontend/src/constants/index.ts
  frontend/src/mocks/handlers/teamHandlers.js
  frontend/src/pages/InvitePage/hooks/useCheckLogin.tsx
  frontend/src/pages/InvitePage/hooks/useCheckTeamJoined.tsx
  frontend/src/pages/InvitePage/hooks/useJoinTeamWithInviteToken.tsx
  frontend/src/pages/InvitePage/hooks/useTeamDetailWithInviteToken.tsx
  frontend/src/pages/InvitePage/index.tsx
  frontend/src/pages/KakaoRedirectPage/index.tsx
  frontend/src/pages/LoginPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/InviteModal.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameCreateModalForm.tsx
  frontend/src/pages/TeamDetailPage/hooks/useCreateInviteLink.tsx
Labels: 프론트엔드, 기능

#344 feat: 메시지 작성 시 비밀글/익명을 선택할 수 있게 한다
  frontend/src/api/message.ts
  frontend/src/mocks/dummy/rollingpapers.json
  frontend/src/mocks/handlers/messageHandlers.js
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/src/pages/RollingpaperPage/components/MessageBox.stories.jsx
  frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
  frontend/src/pages/RollingpaperPage/components/MessageColorPicker.tsx
  frontend/src/pages/RollingpaperPage/components/MessageCreateForm.tsx
  frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
  frontend/src/pages/RollingpaperPage/components/MessageUpdateForm.tsx
  frontend/src/pages/RollingpaperPage/components/RollingpaperMessage.tsx
  frontend/src/pages/RollingpaperPage/components/SecretMessage.tsx
  frontend/src/pages/RollingpaperPage/hooks/useCreateMessage.tsx
  frontend/src/pages/RollingpaperPage/hooks/useDeleteMessage.tsx
  frontend/src/pages/RollingpaperPage/hooks/useMessageBox.tsx
  frontend/src/pages/RollingpaperPage/hooks/useMessageForm.tsx
  frontend/src/pages/RollingpaperPage/hooks/useMessageTextArea.tsx
  frontend/src/pages/RollingpaperPage/hooks/useMessageWrite.tsx
  frontend/src/pages/RollingpaperPage/hooks/useSliceMessageList.tsx
  frontend/src/pages/RollingpaperPage/hooks/useUpdateMessage.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 기능

#350 feat: 모임/개인에게 롤링페이퍼 작성을 위한 UI를 구현
  frontend/src/constants/index.ts
  frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperCreationPage/components/RecipientBox.tsx
  frontend/src/pages/RollingpaperCreationPage/components/TeamRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useReadTeamMembers.tsx
  frontend/src/pages/RollingpaperCreationPage/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, UI

#358 fix: 잘못된 초대링크 수정
  frontend/src/pages/TeamDetailPage/components/InviteModal.tsx
Labels: 프론트엔드, 버그

#347 fix: 모임에게 작성하는 롤링페이퍼의 메시지일 경우 비밀 옵션을 걸지 못하도록 수정
  backend/src/docs/asciidoc/errorCodes.adoc
  backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Rollingpaper.java
  backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidSecretMessageToTeam.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MessageAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/MessageTest.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/RollingpaperTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
Labels: 백엔드, 버그, 기능

#354 feat: 모임 가입할 때, 이미 존재하는 닉네임으로 가입하지 못하도록 기능 추가
  backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
Labels: 백엔드, 버그, 기능

#361 feat: 모임 롤링페이퍼 추가 기능을 추가
  frontend/src/api/rollingpaper.ts
  frontend/src/components/AutoCompleteInput.tsx
  frontend/src/hooks/useAutoCompleteInput.tsx
  frontend/src/mocks/handlers/rollingpaperHandlers.js
  frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperCreationPage/components/TeamRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useCreateMemberRolliingpaper.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useCreateTeamRollingpaper.tsx
  frontend/src/pages/RollingpaperCreationPage/hooks/useReadTeamMembers.tsx
Labels: 프론트엔드, 기능

#364 feat: 비공개 모임, 비밀글 UI 추가
  frontend/src/api/team.ts
  frontend/src/assets/icons/bx-lock-alt.svg
  frontend/src/mocks/handlers/teamHandlers.js
  frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
  frontend/src/pages/TeamSearchPage/components/SearchResultItem.stories.jsx
  frontend/src/pages/TeamSearchPage/components/SearchResultItem.tsx
  frontend/src/pages/TeamSearchPage/components/SearchResultListItem.stories.jsx
  frontend/src/pages/TeamSearchPage/components/SearchResultListItem.tsx
  frontend/src/pages/TeamSearchPage/index.tsx
Labels: 프론트엔드, UI

#366 refactor: 메세지 조회시 모임 대상도 조회할 수 있도록 수정
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/MessageJpaDao.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
Labels: 백엔드, 버그, 기능

#372 fix: 초대링크로 가입에 닉네임 유효성 검사 추가
  frontend/src/components/LineButton.tsx
  frontend/src/pages/InvitePage/index.tsx
Labels: 프론트엔드, 버그

#371 refactor: 메세지 조회시 모임 대상도 조회할 수 있도록 수정
  backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/MessageJpaDao.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
Labels: 백엔드, 버그, 기능

#374 feat: 누락된 refetch 해결
  frontend/src/hooks/useParamValidate.tsx
  frontend/src/hooks/useValidatedParam.tsx
  frontend/src/pages/InvitePage/index.tsx
  frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperCreationPage/components/TeamRollingpaperCreateForm.tsx
  frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
  frontend/src/pages/RollingpaperPage/components/MessageCreateForm.tsx
  frontend/src/pages/RollingpaperPage/hooks/useUpdateMessage.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
  frontend/src/pages/TeamDetailPage/components/InviteModal.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameCreateModalForm.tsx
  frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
  frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
  frontend/src/pages/TeamDetailPage/index.tsx
Labels: 프론트엔드, 버그, 리팩토링

#378 feat: github action ci를 구현한다.
  .github/workflows/ci-backend.yml
  .github/workflows/ci-frontend.yml
Labels: 프론트엔드, 백엔드, 인프라, 설정

#376 fea: 마이페이지의 paging 위치를 고정
  frontend/src/pages/MyPage/components/MessageList.tsx
  frontend/src/pages/MyPage/components/RollingpaperList.tsx
Labels: 프론트엔드, 리팩토링, UI

#381 fix: 모임 롤링페이퍼의 MessageForm에서 비밀글 체크박스를 제거한다.
  frontend/src/mocks/dummy/rollingpapers.json
  frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
  frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
  frontend/src/pages/RollingpaperPage/components/MessageCreateForm.tsx
  frontend/src/pages/RollingpaperPage/components/MessageForm.tsx
  frontend/src/pages/RollingpaperPage/components/MessageUpdateForm.tsx
  frontend/src/pages/RollingpaperPage/hooks/useMessageForm.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 버그, UI

#382 feat: sonarqube 연동
  .github/workflows/sonarqube.yml
  backend/build.gradle
Labels: 백엔드, 인프라, 설정

#379 feat: 초대 토큰의 형식을 JWT에서 AES256으로 변경한다.
  backend/src/main/java/com/woowacourse/naepyeon/exception/InviteTokenInvalidSecretKeyException.java
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/TeamResponseDto.java
  backend/src/main/java/com/woowacourse/naepyeon/support/InviteTokenProvider.java
  backend/src/main/java/com/woowacourse/naepyeon/support/invitetoken/InviteTokenProvider.java
  backend/src/main/java/com/woowacourse/naepyeon/support/invitetoken/aes/Aes256InviteTokenProvider.java
  backend/src/main/java/com/woowacourse/naepyeon/support/invitetoken/aes/Aes256Supporter.java
  backend/src/main/java/com/woowacourse/naepyeon/support/invitetoken/dto/InviteTokenPayload.java
  backend/src/main/resources/application-deploy.yml
  backend/src/main/resources/application-develop.yml
  backend/src/main/resources/application-flywayTest.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/TeamControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/RollingpaperServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/TeamServiceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/support/InviteTokenProviderTest.java
  backend/src/test/java/com/woowacourse/naepyeon/support/invitetoken/aes/Aes256SupporterTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/log4j2.yml
Labels: 백엔드, 기능, 리팩토링

#384 fix: build error 해결
  frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
  frontend/src/pages/RollingpaperPage/components/MessageCreateForm.tsx
  frontend/src/pages/RollingpaperPage/index.tsx
Labels: 프론트엔드, 버그

#390 fix: `.github`변경은 소나큐브 분석 무시하도록 변경
  .github/workflows/sonarqube.yml
Labels: 버그, 인프라, 설정

#392 fix: 메시지 수정시 secret, anonymous 누락 된 부분을 추가한다.
  backend/src/main/java/com/woowacourse/naepyeon/controller/MessageController.java
  backend/src/main/java/com/woowacourse/naepyeon/controller/dto/MessageUpdateRequest.java
  backend/src/main/java/com/woowacourse/naepyeon/domain/Message.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/JpaMessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/repository/MessageRepository.java
  backend/src/main/java/com/woowacourse/naepyeon/service/MessageService.java
  backend/src/main/java/com/woowacourse/naepyeon/service/dto/MessageUpdateRequestDto.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceFixture.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MessageAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/document/MessageControllerTest.java
  backend/src/test/java/com/woowacourse/naepyeon/domain/MessageTest.java
  backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
  backend/src/test/java/com/woowacourse/naepyeon/service/MessageServiceTest.java
  backend/src/test/resources/json/messages/message-create.json
  backend/src/test/resources/json/messages/message-update.json
Labels: 백엔드, 버그, 리팩토링

#391 refactor: 초대코드 암호화 알고리즘을 DES로 변경한다.
  backend/src/main/java/com/woowacourse/naepyeon/support/invitetoken/des/DesInviteTokenProvider.java
  backend/src/main/java/com/woowacourse/naepyeon/support/invitetoken/des/DesSupporter.java
  backend/src/main/resources/application-deploy.yml
  backend/src/main/resources/application-develop.yml
  backend/src/main/resources/application-flywayTest.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/support/invitetoken/aes/Aes256SupporterTest.java
  backend/src/test/java/com/woowacourse/naepyeon/support/invitetoken/des/DesSupporterTest.java
  backend/src/test/resources/application.yml
Labels: 백엔드, 기능, 리팩토링

#388 feat: PR마다 Jest test를 수행하도록 github action 설정
  .github/workflows/frontend-test.yml
  frontend/__tests__/MainPage.test.tsx
  frontend/__tests__/config_util/fileTransformer.js
  frontend/cypress.config.ts
  frontend/cypress/e2e/MainPage.cy.js
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/jest.config.js
  frontend/package.json
  frontend/yarn.lock
Labels: 프론트엔드, 설정, 테스트

#394 fix: 초대코드 URL 인코딩으로 변경
  backend/src/main/java/com/woowacourse/naepyeon/support/invitetoken/aes/Aes256InviteTokenProvider.java
  backend/src/main/java/com/woowacourse/naepyeon/support/invitetoken/aes/Aes256Supporter.java
  backend/src/main/resources/application-deploy.yml
  backend/src/main/resources/application-develop.yml
  backend/src/main/resources/application-flywayTest.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/AcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/acceptance/MessageAcceptanceTest.java
  backend/src/test/java/com/woowacourse/naepyeon/support/InviteTokenProviderTest.java
  backend/src/test/java/com/woowacourse/naepyeon/support/invitetoken/aes/Aes256SupporterTest.java
  backend/src/test/java/com/woowacourse/naepyeon/support/invitetoken/des/DesSupporterTest.java
  backend/src/test/resources/application.yml
Labels: 백엔드, 버그, 리팩토링

#398 feat: flyway를 0.4.0로 업데이트한다.
  backend/src/main/resources/db/migration/V0.4.0__sprint4.sql
Labels: 백엔드, 인프라, 기능

#400 feat: 모임 참여시 refetch 안되는 문제 해결
  frontend/src/pages/TeamDetailPage/components/NicknameCreateModalForm.tsx
Labels: 프론트엔드, 버그

#407 hotfix: inviteJoin시 Transactional 관련 버그를 수정한다.
  backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
Labels: 백엔드, 버그, 리팩토링, 중요
